UpdateHub/updatehub

utils/copy_test.go

The binary being executed didn't expect anything on stdin, so
sometimes its execution was finished before we even write something on
that stdin, leading to a write in a broken pipe.
Now the binary do a "read" command to force the use of stdin, as it is
expected to do so.
Fixes #12.

Fixes intermittent broken pipe error

---

.travis.yml

In the CI context it's actually better if we stick to a short report.

Run tests non-verbosely

---

activeinactive/activeinactive_test.go
installmodes/copy/copy_test.go
installmodes/flash/flash_test.go
installmodes/imxkobs/imxkobs_test.go
installmodes/raw/raw_test.go
installmodes/tarball/tarball_test.go
installmodes/ubifs/ubifs_test.go
testsmocks/cmdlinemock/executer.go
testsmocks/copymock/copy.go
testsmocks/filemock/file.go
testsmocks/filesystemmock/backend.go
testsmocks/filesystemmock/helper.go
testsmocks/libarchivemock/libarchive.go
testsmocks/mtdmock/mtd.go
testsmocks/ubifsmock/ubifs.go
utils/copy_test.go
utils/ubifs_test.go

This will help avoid import cycles with the testsmocks package.

Create new package for each mock

---

states_test.go

Don't multiply elapsed by seconds cause it is already in duration

---

installifdifferent/installifdifferent.go
installifdifferent/installifdifferent_test.go
installmodes/copy/copy.go
installmodes/copy/copy_test.go
installmodes/flash/flash.go
installmodes/flash/flash_test.go
installmodes/imxkobs/imxkobs.go
installmodes/imxkobs/imxkobs_test.go
installmodes/raw/raw.go
installmodes/raw/raw_test.go
metadata/object.go
states.go
states_test.go
testsmocks/installifdifferentmock/installifdifferent.go

This change includes the major logic of the install-if-different
feature. What is still missing is the specific implementations of
comparations between the target and the sha256sum or pattern received
through json. FIXMEs were left in the code indicating this.
I think it is better to merge this partial implementation now because
this impacts directly on the architecture. The part missing won't
affect nothing else so we can develop it with less conflicts.

install-if-different partial implementation

---

constants.go

Fix systemSettingsPath, runtimeSettingsPath and firmwareMetadataDirPath
to use correct system location path.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>

constants: Fix UpdateHub settings and metadata path

---

client/update_test.go
copy/copy.go
copy/copy_test.go
installmodes/copy/copy.go
installmodes/copy/copy_test.go
installmodes/raw/raw.go
installmodes/raw/raw_test.go
installmodes/tarball/tarball.go
installmodes/tarball/tarball_test.go
installmodes/ubifs/ubifs.go
installmodes/ubifs/ubifs_test.go
testsmocks/copymock/copy.go
updatehub/states_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go
utils/constants.go

This way the "updatehub-server" doesn't need to link with libarchive.

move libarchive linkage to the "copy" package

---

updatehub/settings.go
updatehub/settings_test.go
updatehub/states.go
updatehub/states_test.go

It was configured to 3,6 microsseconds and it was leading to a
division by zero.

fixes default polling interval

---

server/agent_backend.go
server/agent_backend_test.go
updatehub/cancellable_state.go
updatehub/daemon_test.go
updatehub/states.go
updatehub/states_test.go

By cancelling the current state and passing the next one as argument
to the Cancel method.

fixes "/update" HTTP API route

---

testsmocks/controllermock/controller.go
testsmocks/controllermock/controller_test.go
testsmocks/reportermock/reporter.go
testsmocks/reportermock/reporter_test.go
updatehub/daemon_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

It should be reported only if the new status is different than the
previous status reported.

fixes status being reported every change

---

client/update_test.go
doc/agent-http.apib
metadata/common_test.go
metadata/firmware.go
metadata/firmware_test.go
metadata/update.go
server/agent_backend_test.go
server/server_backend_test.go
updatehub/updatehub_test.go

- on update metadata, "hardware-revision" doesn't exist anymore,
instead, the "hardware" string will include the revision too
- "supported-hardware" it is an array os strings instead of an array
of objects and each string corresponds to a hardware
- corner-case: when "supported-hardware" is just the string "any"
instead of an array of strings, any hardware will be supported

update "supported-hardware" syntax and behavior

---

cmd/updatehub/constants.go
cmd/updatehub/main.go
cmd/updatehub/main_test.go
server/agent_backend_test.go
updatehub/settings.go
updatehub/settings_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

This is applied on the runtime settings path and the firmware
metadata path.

make paths indirections of system settings

---

cmd/updatehub/constants.go
cmd/updatehub/main.go
doc/agent-http.apib
server/agent_backend.go
server/agent_backend_test.go
server/server_backend_test.go
testsmocks/responsewritermock/responsewriter.go
testsmocks/responsewritermock/responsewriter_test.go
updatehub/cancellable_state.go
updatehub/daemon.go
updatehub/daemon_test.go
updatehub/idle_state_test.go
updatehub/installed_state_test.go
updatehub/installing_state_test.go
updatehub/poll_state_test.go
updatehub/settings.go
updatehub/settings_test.go
updatehub/states.go
updatehub/updatehub.go
updatehub/updatehub_test.go
updatehub/updateprobe_state.go
updatehub/updateprobe_state_test.go

- several HTTP routes removed
- callbacks added
-- State change ("/usr/share/updatehub/state-change-callback"): is
executed before and after a state is handled. Ex.:
<callback> enter <state>
<callback> leave <state>
-- Error ("/usr/share/updatehub/error-callback"): is executed every
time an error is handled. Ex.:
<callback> error_message

HTTP API refactoring

---

client/report.go
client/report_test.go
testsmocks/reportermock/reporter.go
testsmocks/reportermock/reporter_test.go
updatehub/daemon_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

The report JSON now also sends the field "previous-state". Useful on
error cases to discover where the error happened.

report previous state

---

cmd/updatehub/main.go
cmd/updatehub/main_test.go

"Merging" manually. This is because we can't control which setting has
priority over the other on the same key. Mergo always consider
priority the non-zero values.

cmd/updatehub/main.go: don't use mergo to merge settings

---

cmd/updatehub/constants.go
cmd/updatehub/main.go
updatehub/poll_state_test.go
updatehub/settings.go
updatehub/settings_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

They are procedures and not states, they are not reportable and
they run only once before the state machine starts.
When a "installed" state is achieved, it writes in the settings
the "UpgradeToInstallation"=? pointing to the new installation
index.
On the agent start, both validate and rollback states are ignored
when the "UpgradeToInstallation" is < 0 (-1 is the default value
when it's not set).
If "UpgradeToInstallation" is >= 0 AND is different from the current
active installation, a rollback procedure is launched. It just calls
the rollback callback and then go back to the state machine.
If "UpgradeToInstallation" is >= 0 AND is equal to the current active
installation, a validate procedure is launched. The validate procedure
calls the validate callback, if the callback succeeds, …

implement validate and rollback procedures

---

.travis.yml

.travis.yml: add go 1.9 to the test matrix

---

server/server_backend.go
server/server_backend_test.go

Since libarchive doesn't support seek, we need to be careful when
using the "libarchive.Reader" struct. We need te create a new Reader
struct every time we do an extraction so we ensure the internal
pointer of the archive is reset. On uhupkg files this doesn't impact
on performance since it uses "zip" format on which the files are
indexed.
The server backend implementation was already correct but a test was
missing to ensure that.

ensure that the same object can be downloaded twice

---

cmd/updatehub-server/main.go

updatehub-server: force usage of http instead of https

---

updatehub/updatehub_test.go
utils/sha.go

This avoids high memory usage when reading huge file

FileSha256sum: Copy bytes from reader to writer instead of reading entire file

---

client/client.go

The timeout should not take into account the full body being read to
about the connection, specially on small timeouts.
This commit changes the following timeouts:
Dial:             30s
Keep Alive:       30s
TLS hand shake:   30s
Response headert: 30s
Expect continue:  1s

client: Fix net/http timeout

---

server/agent_backend.go
server/agent_backend_test.go

CheckRedirect is setted to nil because when comparing two structs with
non-nil function pointer, reflect.DeepEqual will return false.
See discussion about this behaviour here: https://github.com/golang/go/issues/8554

server: create a instance of apiclient when server-address is given

---

updatehub/probe_state.go

ProbeState: disable ASAP mode in case of ProbeUpdate success

---

activeinactive/activeinactive.go
testsmocks/activeinactivemock/activeinactive.go
testsmocks/activeinactivemock/activeinactive_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

This allows to reset 'upgrade_available' to zero by calling update-active-activated script from 'validateProcedure'.
(based on PR #195 )

activeinactive: implement 'SetValidate' function

---

cmd/updatehub/main.go
updatehub/updatehub.go

Without this commit, the agent code reading 'UpgradeToInstallation'
from '/etc/updatehub.conf' and not from persistents data (/data)
Also fixes the update of 'UpgradeToInstallation' after an update.
Fixes #197
Signed-off-by: Pierre-Jean TEXIER <texier.pj2@gmail.com>

fixes load and update of UpgradeToInstallation variable

---

cmd/updatehub/main.go

Allow updatehubhub to have their own per-process private filesystem
mount points

updatehub: unshare mount namespace

---

cmd/updatehub-server/udev.rules

Udev cannot mount this once UpdateHub server mounts device in
/mnt/updatehub.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>

updatehub-server: Remove mount command from udev rule

---

copy/copy.go

In case of cancellation or a read error, we need to stop the copy. The
condition is wrong as we should return as soon as possible.

copy: The return should be done even if `ok` fail

---

installmodes/tarball/tarball.go
installmodes/tarball/tarball_test.go

Also removes some specific tests for umount errors in install method
since it is already tested in cleanup tests

installmodes/tarball: umount device only in cleanup method

---

cmd/updatehub-server/main.go

updatehub-server: replace --wait option with --probe

---

cmd/updatehub-server/udev.rules

Use --ignore-probe-asap option when start updatehub-server.

updatehub-server: udev.rules: Add --ignore-probe-asap option

---

doc/agent-http.yaml
updatehub/src/http_api.rs
updatehub/src/states/actor/mod.rs
updatehub/src/states/actor/remote_install.rs
updatehub/src/states/direct_download.rs
updatehub/src/states/idle.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs

We now have a new state on the machine's agent `DirectDownload` that will
download the specified package from the link and will then move to the
`PrepareLocalInstall` state in order to install the required package.
The agent's API now has a new route where the user can request for a package
to be installed from a remote URL which is not an Updatehub Server

general: Add support for installing package from url

---

Cargo.lock
updatehub/Cargo.toml

We update the actix to use from upstream Git and nix crates. After that,
also update inner dependencies.
This should fix the GitHub actions failure as our actix fork has been changed.

general: Update all dependencies

---

updatehub/src/utils/definitions.rs

The Nix crate now allow to find the User and Group numeric id from its
name. This internally still uses unsafe code but it goes a long way to
avoid undefined behavior so we better use it.

utils: Replace unsafe code with Nix new User and Group methods

---

updatehub-sdk/src/api/mod.rs
updatehub-sdk/src/client/mod.rs
updatehub/src/main.rs
updatehub/src/mem_drain.rs
updatehub/src/states/actor/local_install.rs
updatehub/src/states/actor/remote_install.rs
updatehub/src/states/install.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs
updatehub/src/states/poll.rs
updatehub/src/states/prepare_download.rs
updatehub/src/states/prepare_local_install.rs
updatehub/src/states/probe.rs

* Renamed `cli` subcommand to `client`;
* Finished client subcommands;
* Fixed some api specifications on SDK;
* Fixed directory creation for `prepare_local_install` state;
* Reworked points where buffered log gets started and cleared so user queries are more informative;

Update from dev branch

---

updatehub/src/states/actor/mod.rs
updatehub/src/states/probe.rs

updatehub: Add test to ensure fail on custom probe to invalid url

---

updatehub/src/logger.rs
updatehub/src/states/actor/local_install.rs
updatehub/src/states/actor/remote_install.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs
updatehub/src/states/poll.rs
updatehub/src/states/probe.rs

This also removes the 'start_logging' on probe state, as it is already started on http requests and on polling state

updatehub: Avoid explicit locking of logger buffer

---

Cargo.lock
updatehub-sdk/Cargo.toml
updatehub-sdk/src/client/mod.rs
updatehub-sdk/src/error.rs
updatehub/Cargo.toml
updatehub/src/client/mod.rs
updatehub/src/firmware/mod.rs
updatehub/src/http_api.rs
updatehub/src/lib.rs
updatehub/src/object/mod.rs
updatehub/src/runtime_settings.rs
updatehub/src/settings.rs
updatehub/src/states/mod.rs
updatehub/src/states/prepare_local_install.rs
updatehub/src/update_package/mod.rs
updatehub/src/utils/mod.rs

The use of thiserror allow us to properly implement std::error::Error
and better use the ecosystem.

Convert error types to thiserror crate

---

updatehub/src/runtime_settings.rs
updatehub/src/states/install.rs

This way of selecting the inactive installation set will work even if one
package has already been installed but the agent has not yet restarted

updatehub: Get inactive installation set from RuntimeSettings

---

Cargo.lock
updatehub/Cargo.toml
updatehub/src/object/installer/copy.rs
updatehub/src/object/installer/flash.rs
updatehub/src/object/installer/imxkobs.rs
updatehub/src/object/installer/mod.rs
updatehub/src/object/installer/raw.rs
updatehub/src/object/installer/tarball.rs
updatehub/src/object/installer/ubifs.rs
updatehub/src/object/macros.rs
updatehub/src/utils/fs.rs

Add check_if_different helper function to object::installer module. Function is
used on install modes that support install_if_different rule so we can skip
installation if requested

updatehub: Use install_if_different rule

---

Cargo.lock
updatehub/Cargo.toml
updatehub/src/object/info.rs
updatehub/src/object/installer/mod.rs
updatehub/src/states/download.rs
updatehub/src/update_package/mod.rs
updatehub/src/utils/mod.rs

We are using the OpenSSL anyway and it can be used to do the sha256sum,
so we are dropping the crypto-hash crate which were used for this.
While doing that, we found that converting to hex is simple enough so we
also dropped hex use as well.

Remove use of crypto-hash and hex crates

---

updatehub-sdk/src/api/mod.rs
updatehub/src/http_api.rs
updatehub/src/states/actor/download_abort.rs
updatehub/src/states/actor/info.rs
updatehub/src/states/actor/local_install.rs
updatehub/src/states/actor/mod.rs
updatehub/src/states/actor/probe.rs
updatehub/src/states/actor/remote_install.rs
updatehub/src/states/actor/test.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs
updatehub/src/states/prepare_download.rs
updatehub/src/states/probe.rs
updatehub/src/states/validation.rs
updatehub/src/update_package/mod.rs

This also rework some of the internal code structure.
* general: Make last_poll always present
* general: Rework extra_interval handling logic
* updatehub: Update poll handle logic
* updatehub: Register last polling even if validation fails
* updatehub: Move update package validation to it's own state
* updatehub: Rename generic state runner to for_current_state
* updatehub: Rework actor current message handling logic
* updatehub: use expect for Machine's state on message handles
* updatehub: Unexpose http_api internal error
* sdk: Make api::probe::Response try again field optional
* updatehub: Rework trigger probe request

updatehub: Rework trigger probe request

---

updatehub/src/client/mod.rs
updatehub/src/states/direct_download.rs
updatehub/src/states/mod.rs

The `get` function is used to get a body from a remote link and save it to any
`AsyncWrite` while logging the progress of the download. This is used both on
`client::Api` to download objects and on the `DirectDownload` state

updatehub: Add get function to client module

---

updatehub/src/states/mod.rs
updatehub/src/states/tests.rs

The rollback callback is now executed on the new installed image, this allows
the scripts to fix (i.e. rollback) any modifications to the system caused by
the faulty installation of the new image

updatehub: Run rollback callback on new image

---

doc/agent-http.yaml
updatehub-sdk/src/client/mod.rs
updatehub-sdk/tests/openapi_integration.rs
updatehub/src/main.rs

general: Use json for requests on remote_install and local_install

---

updatehub-sdk/src/api/mod.rs
updatehub-sdk/src/client/mod.rs
updatehub/src/http_api.rs

This fixes the Agent's client SDK not being able to communicate with the updatehub local server due to the API change on #267.

updatehub: Use request types from sdk

---

updatehub/src/states/actor/stepper.rs
updatehub/src/states/download.rs

Download state transition now yields when download is still pending so other
futures in the same event loop can progress. Stepper now uses a non-blocking
wait when delayed transition is requested.

updatehub: Avoid blocking state machine

---

updatehub/src/object/installer/copy.rs
updatehub/src/object/installer/tarball.rs
updatehub/src/states/mod.rs
updatehub/src/states/prepare_local_install.rs
updatehub/src/states/validation.rs

When the device has a signature key setup and the package is not signed a "SingatureNotFound" is raised on the installation process for both downloaded packages and local install.

Threat a missing signature on pkg as an error and clippy note

---

updatehub/src/states/actor/download_abort.rs
updatehub/src/states/actor/local_install.rs
updatehub/src/states/actor/probe.rs
updatehub/src/states/actor/remote_install.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs
updatehub/src/states/poll.rs
updatehub/src/states/prepare_download.rs
updatehub/src/states/probe.rs
updatehub/src/states/validation.rs

This also silently fixes a bug where local install couldn't be triggered while the agent was waiting for the setup time for probing the server. This happens because the state already supported the `trigger_probe` request. Now that the methods have been unified, the state can handle all three requests as intended.

updatehub: Rework StateChangeImpl methods for external messages

---

updatehub/Cargo.toml

This makes development build easier as it wont be necessary to manually add the
feature in order to run tests

updatehub: Add test-env feature to default features

---

updatehub/src/states/macros.rs

This simplify the code avoiding 'if let' construction. This requires
Rust 1.42.0 which is our MSRV.

updatehub: tests: Use 'matches!' macro to simplify code

---

updatehub-cloud-sdk/src/client.rs

This adds a workaround for a segmentation fault that seams to be caused when the client tries to compute the base64 of a empty signature. Bug has been reported on https://github.com/sfackler/rust-openssl/issues/1325.

Add workaround for openssl bug

---

.github/workflows/linux.yml

Last CI fix PR (#305) attempt to ignore cargo bloat execution but one of the steps was missed causing linux build to fail for Rust 1.42. This PR should fix that.

CI: Fix cargo bloat not being ignoring for execution

---

Cargo.lock
updatehub/Cargo.toml

After doing the upgrade we also did the update of the compatible
dependencies so we keep it all up to date.

cargo: Upgrade tide to 0.13

---

updatehub/tests/common.rs

The function search for a available socket to attribute to the
listen_socket variable, instead of a static value as before.

updatehub: Add a function to bind available sockets

---

updatehub/src/object/macros.rs

updatehub: Fix misuse of required size value for uncompressed objects

---

updatehub/src/main.rs
updatehub/tests/common.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

This fix the problem when the socket for server change instead
of the default.

updatehub: Fix the dynamic bind socket for tests

---

Cargo.lock

Following dependencies were updated:
Updating git repository `https://github.com/http-rs/surf`
Adding async-executor v0.1.2
Updating async-h1 v2.1.1 -> v2.1.2
Adding async-io v0.1.11
Adding async-mutex v1.1.5
Updating async-std v1.6.2 -> v1.6.3
Updating async-trait v0.1.36 -> v0.1.37
Updating blocking v0.4.7 -> v0.5.1
Updating chrono v0.4.13 -> v0.4.15
Removing compress-tools v0.5.1
Updating concurrent-queue v1.2.0 -> v1.2.2
Updating data-encoding v2.2.1 -> v2.3.0
Updating event-listener v2.3.0 -> v2.3.3
Updating fastrand v1.3.3 -> v1.3.4
Updating femme v2.1.0 -> v2.1.1
Updating find-binary-version v0.3.1 -> v0.3.2
Updating futures-lite v0.1.10 -> v0.1.11
Updating generic-array v0.14.3 -> v0.14.4
Updating http-types v2.3.0 -> v2.4.0
Adding multitask v0.2.0
Adding parking v2.0.0
Adding …

cargo: Update all dependencies

---

updatehub/src/states/direct_download.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/error.rs
updatehub/src/states/install.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs
updatehub/src/states/poll.rs
updatehub/src/states/prepare_local_install.rs
updatehub/src/states/probe.rs
updatehub/src/states/reboot.rs
updatehub/src/states/validation.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

Some changes to where state change callback is called and some minor code fixes

states: Add state change callback for error state and minor fixes

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
.github/workflows/linux.yml
Cargo.lock
updatehub-cloud-sdk/Cargo.toml
updatehub-cloud-sdk/src/client.rs
updatehub-sdk/Cargo.toml
updatehub-sdk/src/client.rs
updatehub/Cargo.toml

Today surf 2.0.0 was released and this PR does the work to update it, as well as
the other dependencies of whole project.
----
#

Update all dependencies, including surf 2.0.0

---

updatehub/src/states/machine/mod.rs
updatehub/src/states/poll.rs
updatehub/src/states/probe.rs

We are already using the `chrono::Duration` and limiting the use of
`std::time::Duration` to the internal sleeping of the tasks.

updatehub: Refactor code to use `chrono::Duration`

---

updatehub-cloud-sdk/src/client.rs
updatehub/src/cloud_mock.rs
updatehub/src/states/machine/mod.rs
updatehub/src/states/probe.rs

We can avoid the use of casting (for u64), which can in fact fail, using `usize`
for the number of probe retries. The `usize` use here seems a good fit
as it matches the word size of the current in-use CPU architecture.

cloud-sdk: Use `usize` for number of `probe` retries

---

updatehub-cloud-sdk/src/client.rs
updatehub/src/firmware/mod.rs
updatehub/src/states/error.rs

We have a very robust logging system now and any error is also emitted
to the normal `state_change_callback`. This avoids two ways of handling
same information and drop some complexity for users.

updatehub: states: Drop `error_callback` support

---

Cargo.lock
updatehub-cloud-sdk/src/lib.rs
updatehub/Cargo.toml
updatehub/src/firmware/mod.rs
updatehub/src/object/mod.rs
updatehub/src/runtime_settings.rs
updatehub/src/settings.rs
updatehub/src/states/mod.rs

This does a global update of dependencies. This raises the new error coming from `derive_more`, which is stricter about its macro use. The PR fixes it as well.

Upgrade all dependencies

---

updatehub/src/firmware/tests.rs
updatehub/src/runtime_settings.rs
updatehub/src/states/machine/mod.rs
updatehub/src/states/mod.rs
updatehub/src/states/tests.rs
updatehub/src/tests.rs
updatehub/tests/common.rs
updatehub/tests/successful_integration_test.rs

This branch intends to fix the error when coming from an existing v1 upgrade. This is done by loading the previous version context into the new data structure and then using the usual code path to run the business logic.
The following tasks need to be complete prior to merging this:

Add support to parse "v1" runtime settings

---

updatehub/src/states/mod.rs
updatehub/src/states/prepare_local_install.rs

When doing local installations the Install state can take too long to
be triggered. Now we can check the PrepareLocalInstall for faster
feedback.

updatehub: states: Add callback support for PrepareLocalInstall

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
.github/workflows/linux.yml

Nightly version fixed till rexpect doesn't fail on nightly. Tracking issue has been opened on: https://github.com/philippkeller/rexpect/issues/38

CI: Pin down nightly version to avoid execution erros from rexpect

---

updatehub/src/states/machine/mod.rs
updatehub/src/states/mod.rs
updatehub/src/states/probe.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

- updatehub: states: probe: set last polling when state is cancelled
- updatehub: states: machine: fix typo
- updatehub: states: machine: use 0 seconds as delaying default time
- updatehub: fix spelling of 'canceling' in error messages

Improve probe callback handling

---

Cargo.lock

slog-term on 2.9.0 doesn't compile due to a  problem with the time library that requires a type annotation on the usage of Box smart pointer.

cargo: downgrade slog-term and update proc-macro2
