UpdateHub/updatehub

libarchive/libarchive.go

Improve libarchive "la_" prefix fix for older versions

---

utils/mtd.go

Fix mtd api usage for older kernels

---

.travis.yml

Travis-CI: Add Coverrals integration

---

main.go
states.go
states_test.go
updatehub.go
updatehub_test.go

Use polling interval value from settings file

---

glide.lock
glide.yaml
main.go
states.go
states_test.go
updatehub.go

Do the first polling in a random interval

---

states.go
states_test.go

Auto-trigger delayed polling on startup

---

.travis.yml

Run gometalinter before testing

---

metadata/update.go
states.go
states_test.go
updatehub.go

And "InstallingState" and "WaitingForRebootState" and "InstalledState"
prototypes. These are required for the "InstallState" implementation.

Add InstallState initial implementation

---

main.go
states.go
states_test.go
updatehub.go
updatehub_test.go

polling refactoring: remove initial state definition logic from PollState

---

updatehub_test.go

TestStartPolling: unpatch time.Now after tests run

---

main.go
states.go
states_test.go

add new idle state

---

activeinactive/activeinactive.go
activeinactive/activeinactive_test.go
installmodes/copy/copy.go
installmodes/internal/testsutils/utils.go
installmodes/tarball/tarball.go
metadata/update_test.go
states.go
states_test.go
testsmocks/activeinactivemock/activeinactive.go
testsmocks/objectmock/object.go
utils/error.go
utils/error_test.go

This includes the ActiveInactive feature

Add InstallingState initial implementation

---

states.go

PollState: avoid state change when polling is disabled

---

installmodes/copy/copy.go
installmodes/copy/copy_test.go
installmodes/flash/flash.go
installmodes/flash/flash_test.go
installmodes/imxkobs/imxkobs.go
installmodes/imxkobs/imxkobs_test.go
installmodes/internal/testsutils/utils.go
installmodes/raw/raw.go
installmodes/raw/raw_test.go
installmodes/tarball/tarball.go
installmodes/tarball/tarball_test.go
installmodes/ubifs/ubifs.go
installmodes/ubifs/ubifs_test.go

Add missing headers

---

states.go
states_test.go

This change was made to enable PollState to be cancelled outside
PollState handling logic

Use time.Ticker instead of time.Sleep

---

client/update.go
settings.go
settings_test.go
states.go
states_test.go
updatehub.go
updatehub_test.go

convert ints to time types

---

states.go
states_test.go

PollState: change to update-check state after ticks are delivered

---

states.go
states_test.go
testsmocks/objectmock/object.go
testsmocks/statesmock/sha256checker.go

Check sha256sum before installation

---

main.go
metadata/common_test.go
metadata/firmware.go
metadata/firmware_test.go
metadata/update.go
metadata/update_test.go
states.go
states_test.go

Check supported hardware on UpdateInstallState

---

states.go
states_test.go

UpdateCheckState: switch to PollState in case of extra polling response

---

states.go
states_test.go

states: switch to update-check state if extra polling time is before now

---

updatehub.go
updatehub_test.go

startPolling: set poll state interval to the pending extra poll interval

---

daemon.go
daemon_test.go
main.go
states.go
updatehub.go

main: move mainloop implementation to a separate file

---

states.go
states_test.go
updatehub.go

NewPollState: creates a new pollstate with a predefined interval

---

daemon.go
daemon_test.go
main.go
updatehub.go

Improve error logging from ReportCurrentState

---

daemon.go

Use logger to warn errors

---

.travis.yml
main.go

main: log error from LoadSettings

---

libarchive/libarchive.go
libarchive/libarchive_test.go

libarchive: fixes not "chdir"ing back after an extractTarball error

---

metadata/firmware.go
states.go

remove already implemented FIXMEs

---

utils/mtd_test.go

utils/mtd.go: improve coverage

---

daemon_test.go
installifdifferent/installifdifferent.go
installifdifferent/installifdifferent_test.go
metadata/update.go
metadata/update_test.go
states.go
states_test.go
testsmocks/updatermock/updater.go
updatehub.go
updatehub_test.go
utils/sha.go
utils/sha_test.go

And not always the first one in the list

make fetchupdate download the active-inactive object

---

updatehub.go
updatehub_test.go

updatehub.go: mock Copy on FetchUpdate

---

client/update_test.go

client/update.go: implement tests for FetchUpdate()

---

client/update.go
client/update_test.go
testsmocks/updatermock/updater.go
updatehub.go
updatehub_test.go

client/update.go: implement tests for CheckUpdate()

---

updatehub_test.go

updatehub.go: use mock package to test CheckUpdate()

---

utils/filesystem.go

utils/filesystem.go: Mount and Umount real implementations

---

installmodes/copy/copy.go
installmodes/copy/copy_test.go
installmodes/tarball/tarball.go
installmodes/tarball/tarball_test.go
utils/filesystem.go
utils/filesystem_test.go

utils/filesystem.go: "Format()" real implementation

---

installifdifferent/kernelfileinfo.go
installmodes/copy/copy.go
installmodes/copy/copy_test.go
installmodes/tarball/tarball.go
installmodes/tarball/tarball_test.go
testsmocks/filesystemmock/helper.go
utils/filesystem.go

utils/filesystem.go: "TempDir()" real implementation

---

installmodes/copy/copy.go
installmodes/copy/copy_test.go
testsmocks/permissionsmock/file.go
utils/copy_test.go
utils/file.go
utils/file_test.go

support "target-mode", "target-uid" and "target-gid" for "copy" handler

---

updatehub/updatehub.go
updatehub/updatehub_test.go

updatehub/updatehub.go: make configuration files optional

---

cmd/updatehub-server/main.go
cmd/updatehub/main.go
glide.lock
glide.yaml
server/agent_backend.go
server/agent_backend_test.go
server/backend.go
server/daemon.go
server/daemon_test.go
server/router.go
server/router_test.go
server/server_backend.go
server/server_backend_test.go
updatehub/daemon.go
updatehub/daemon_test.go
updatehub/states.go
updatehub/updatehub.go

use "github.com/OSSystems/pkg/log" as logger

---

README.md

README.md: text improvement

---

doc/agent-http.apib

doc/agent-http.apib: agent HTTP API blueprint documentation

---

cmd/updatehub/main.go
doc/agent-http.apib
metadata/firmware.go
metadata/firmware_test.go
server/agent_backend.go
server/agent_backend_test.go
updatehub/settings.go
updatehub/states.go
updatehub/states_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

HTTP API "/info" route implementation

---

.gitignore
.travis.yml
Makefile
cmd/updatehub/main.go
doc/agent-http.apib
server/agent_backend.go
server/agent_backend_test.go
updatehub/daemon.go
updatehub/updatehub.go

Makefile: create useful targets and use them on travis

---

Makefile

Makefile: fixes lint

---

doc/agent-http.apib
server/agent_backend.go
server/agent_backend_test.go
testsmocks/controllermock/controller.go
testsmocks/controllermock/controller_test.go

HTTP API "/update" route implementation

---

doc/agent-http.apib
server/agent_backend.go
server/agent_backend_test.go

HTTP API "/update/metadata" route implementation

---

server/agent_backend.go
server/agent_backend_test.go

HTTP API "/update/probe" route implementation

---

server/agent_backend.go
server/agent_backend_test.go

HTTP API "/update/download" route implementation

---

cmd/updatehub-server/main.go
cmd/updatehub/main.go
doc/agent-http.apib
glide.lock
glide.yaml
server/agent_backend.go
server/agent_backend_test.go
updatehub/daemon.go
updatehub/daemon_test.go

HTTP API "/log" route implementation

---

activeinactive/activeinactive.go
activeinactive/activeinactive_test.go
client/report.go
client/update.go
client/update_test.go
cmd/updatehub/main.go
copy/copy.go
copy/copy_test.go
installifdifferent/installifdifferent.go
installifdifferent/installifdifferent_test.go
installmodes/copy/copy.go
installmodes/flash/flash.go
installmodes/imxkobs/imxkobs.go
installmodes/raw/raw.go
installmodes/tarball/tarball.go
installmodes/ubifs/ubifs.go
metadata/firmware.go
metadata/object.go
server/agent_backend.go
server/server_backend.go
updatehub/settings.go
updatehub/settings_test.go
updatehub/states.go
updatehub/updatehub.go

improve log messages

---

cmd/updatehub-server/main.go
cmd/updatehub/main.go

add cmdline log options

---

cmd/updatehub-server/main.go
cmd/updatehub/main.go

fixes help not exiting

---

server/agent_backend.go
server/agent_backend_test.go
updatehub/cancellable_state.go
updatehub/daemon.go
updatehub/states.go

HTTP API "/update/download/abort" route implementation finished

---

doc/agent-http.apib
server/agent_backend_test.go
updatehub/settings.go
updatehub/settings_test.go

rename "UpdateHubServerAddress" to "ServerAddress"

---

updatehub/daemon_test.go
updatehub/states.go
updatehub/states_test.go
updatehub/updatehub_test.go

fixes "idle" state being reported

---

cmd/updatehub/main.go

fixes requests being made always to localhost

---

client/update.go
client/update_test.go

client/update.go: add api header to requests

---

cmd/updatehub/main.go
cmd/updatehub/main_test.go

cmd/updatehub/main.go: server address sanitation

---

client/client.go
client/client_test.go
client/report_test.go
client/update_test.go

client/client.go: fixes address sanitation

---

cmd/updatehub/main.go
cmd/updatehub/main_test.go
doc/agent-http.apib
server/agent_backend_test.go
updatehub/settings.go
updatehub/settings_test.go

remove the DisableHTTPS setting

---

cmd/updatehub/main.go
updatehub/updatehub.go
updatehub/updatehub_test.go

cmd/updatehub/main.go: assign activeinactive implementation

---

activeinactive/activeinactive.go
activeinactive/activeinactive_test.go

activeinactive/activeinactive.go: accepts newline on scripts

---

updatehub/updatehub.go
updatehub/updatehub_test.go

updatehub/updatehub.go: fixes download route

---

client/report.go
client/report_test.go
installifdifferent/installifdifferent.go
testsmocks/reportermock/reporter.go
testsmocks/reportermock/reporter_test.go
updatehub/daemon_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

fixes report status

---

installifdifferent/installifdifferent.go
installifdifferent/installifdifferent_test.go
installmodes/copy/copy.go
installmodes/copy/copy_test.go

fixes copy not getting correct target path on install-if-different

---

cmd/updatehub/main.go
updatehub/updatehub.go
updatehub/updatehub_test.go

updatehub/updatehub.go: add NewUpdateHub method

---

metadata/update.go
server/agent_backend.go
server/daemon.go
server/server_backend.go
updatehub/updatehub.go
updatehub/updatehub_test.go

saves update metadata on disk after probe

---

updatehub/states.go
updatehub/states_test.go

updatehub/states.go: fixes "installed" report segfault

---

server/agent_backend.go
server/agent_backend_test.go

report state when calling install through http route

---

installmodes/copy/copy.go
installmodes/copy/copy_test.go

mount and format on "Setup()" and umount on "Cleanup()"

installmodes/copy/copy.go: fixes copy install mode

---

server/server_backend.go
server/server_backend_test.go

server/server_backend.go: fixes server "getObject()" route

---

cmd/updatehub-server/main.go
copy/copy_test.go
libarchive/libarchive.go
server/agent_backend_test.go
server/daemon.go
server/daemon_test.go
server/server_backend.go
server/server_backend_test.go
testsmocks/libarchivemock/libarchive.go
testsmocks/libarchivemock/libarchive_test.go

add support for uhupkg to the server

---

updatehub/states.go
updatehub/states_test.go

fixes busy loop when polling interval is smaller than time step

---

cmd/updatehub/main.go
server/agent_backend.go
server/agent_backend_test.go
updatehub/installed_state.go
updatehub/installed_state_test.go
updatehub/reboot_state.go
updatehub/reboot_state_test.go
updatehub/states.go
updatehub/updatehub.go
updatehub/updatehub_test.go

reboot implementation

---

installmodes/copy/copy.go
installmodes/copy/copy_test.go

create subdirs on target path for copy install mode

---

client/update.go
client/update_test.go
cmd/updatehub/main.go
cmd/updatehub/main_test.go
metadata/update.go
metadata/update_test.go
server/agent_backend_test.go
server/server_backend.go
server/server_backend_test.go
testsmocks/controllermock/controller.go
testsmocks/controllermock/controller_test.go
testsmocks/updatermock/updater.go
testsmocks/updatermock/updater_test.go
updatehub/probe_state.go
updatehub/probe_state_test.go
updatehub/states_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

add support for signature

---

cmd/updatehub/main.go
updatehub/settings.go
updatehub/settings_test.go

verify settings when loading

---

server/server_backend.go
server/server_backend_test.go

Create a new libarchive Reader to ensure signature extraction

---

server/server_backend.go

Set signature header with base64 data

---

updatehub/downloading_state_test.go
updatehub/installing_state_test.go
updatehub/poll_state_test.go
updatehub/probe_state.go
updatehub/probe_state_test.go
updatehub/states_test.go

replace testController with mock

---

cmd/updatehub-ctl/main.go
cmd/updatehub-ctl/types.go
glide.lock
glide.yaml

add updatehub-ctl utility

---

cmd/updatehub-server/main.go

If there is an update available, serve files for update process,
otherwise exit application without error

update-server: probe for update after process startup

---

Makefile

Add target to build updatehub-ctl binary.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>

Makefile: Add updatehub-ctl target

---

cmd/updatehub-server/udev.rules

updatehub-server: add udev rules

---

cmd/updatehub-server/main.go

updatehub-server: update server address port

---

cmd/updatehub-ctl/main.go
server/agent_backend.go

Use server-address from updatehub.conf by default

---

updatehub/updatehub.go

This reverts commit ccb46cf9ac4b0ff3646144b7ddc2e32ad3aabc99, reversing changes made to 99f007f0e734bb478cfddb00216c6779a174a35b.

Revert "Merge pull request #180"

---

updatehub/probe_state.go
updatehub/probe_state_test.go
updatehub/updatehub.go
updatehub/updatehub_test.go

Fix probe ASAP

---

installmodes/flash/flash.go
installmodes/tarball/tarball.go
installmodes/tarball/tarball_test.go
installmodes/ubifs/ubifs.go
mtd/mtd.go
mtd/mtd_test.go
mtd/ubifs.go
mtd/ubifs_test.go

Move mtd and ubifs stuff to a separated package

---

.travis.yml

travis: Add Go 1.10 to the test matrix

---

client/report.go
client/report_test.go

client: also send device-attributes in state report

---

installmodes/mender/mender.go
installmodes/mender/mender_test.go

Add mender installmode

---

client/update_test.go
glide.lock

glide: update project dependecies

---

cmd/updatehub-server/main.go
cmd/updatehub-server/udev.rules
glide.lock
glide.yaml

updatehub-server: add cli options for mounting usb disk

---

cmd/updatehub/main.go

Reverted these commits in order to use `unshare` binary

Revert reexec and unshare commits

---

updatehub/updatehub.go

This reverts commit 5de10abcb6b5f450de168efbafcb02ff4af0a116.

Revert "updatehub: Fix race condition in GetState"

---

updatehub/updatehub.go

updatehub: lock state change mutex in cancel operation

---

updatehub/updatehub.go
updatehub/updatehub_test.go

updatehub: fix invalid command line string

---

installmodes/zephyr/zephyr.go
installmodes/zephyr/zephyr_test.go

Add zephyr installmode

---

cmd/updatehub/main.go
metadata/update.go

Warn when public key is not provided

---

libarchive/libarchive.go
libarchive/libarchive_test.go

libarchive: preserve owner when extracting

---

server/agent_backend.go

server: Prepend dirname to update package filename

---

server/agent_backend.go

server: fix unexpected output of probe command

---

.github/workflows/ci.yml

CI: Run only on main branches and pull requests

---

Cargo.lock
updatehub/Cargo.toml

updatehub: Upgrade actix to 0.10-alpha.1

---

updatehub/src/states/actor/download_abort.rs
updatehub/src/states/actor/mod.rs
updatehub/src/states/actor/test.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/error.rs
updatehub/src/states/install.rs
updatehub/src/states/mod.rs
updatehub/src/states/probe.rs
updatehub/src/states/reboot.rs

updatehub: Rename Idle state to EntryPoint

---

updatehub/src/firmware/mod.rs
updatehub/src/states/error.rs

updatehub: Add support for error callback

---

Cargo.lock
updatehub-sdk/src/api/info/runtime_settings.rs
updatehub-sdk/src/serde_helpers.rs
updatehub/Cargo.toml
updatehub/src/runtime_settings.rs
updatehub/src/states/poll.rs
updatehub/src/states/probe.rs

* general: Make last_poll always present
* general: Rework extra_interval handling logic
* updatehub: Update poll handle logic

Some updates from dev branch

---

Cargo.lock
updatehub-package-schema/Cargo.toml
updatehub-sdk/Cargo.toml
updatehub/Cargo.toml

Reduce the features used so we reduce binary size

---

Cargo.lock
doc/agent-http.yaml
updatehub-sdk/Cargo.toml
updatehub-sdk/src/api/info/firmware.rs
updatehub-sdk/src/api/info/mod.rs
updatehub-sdk/src/api/info/runtime_settings.rs
updatehub-sdk/src/api/info/settings.rs
updatehub-sdk/src/api/mod.rs
updatehub-sdk/src/client/mod.rs
updatehub-sdk/tests/openapi_integration.rs
updatehub/src/main.rs

This add several fixes and update to the current API documentation to make it compatible with what the SDK currently uses.
Integration test has also been added to the SDK that will ensure that's defined there matches that the Swagger OpenAPI doc file specifies.

Update API documentation to current specification on SDK

---

Cargo.lock
Vagrantfile
updatehub/Cargo.toml
updatehub/src/object/info.rs
updatehub/src/object/installer/copy.rs
updatehub/src/object/installer/flash.rs
updatehub/src/object/installer/raw.rs
updatehub/src/object/installer/tarball.rs
updatehub/src/object/installer/ubifs.rs
updatehub/src/object/macros.rs
updatehub/src/object/mod.rs
updatehub/src/utils/fs.rs
updatehub/src/utils/mod.rs

This also adds validation for available storage space before installing any object

Add support for installing compressed objects

---

updatehub/src/runtime_settings.rs

Now, when the agent fails to read or parse the Runtime Settings file, a warning is given to the user, but the application does not crash. It instead will rename said config file to append `.old` to it, and will run with the default settings.

updatehub: Fail safety for badly formatted Runtime Settings file

---

.github/workflows/ci.yml
Cargo.lock
updatehub/Cargo.toml
updatehub/src/settings.rs

This allows deserialization from V1 settings file format

updatehub: Add 'v1-parsing' feature flag

---

README.md

Signed-off-by: Domarys Correa <domarys.correa@ossystems.com.br>

README: Fix presence of the ShellHub term

---

updatehub/Cargo.toml
updatehub/src/states/download.rs
updatehub/src/states/mod.rs
updatehub/src/states/prepare_download.rs

Change the download_chan to async

---

Cargo.lock
updatehub-cloud-sdk/src/client.rs
updatehub-package-schema/Cargo.toml
updatehub-package-schema/src/definitions/install_if_different.rs
updatehub/Cargo.toml
updatehub/src/firmware/hook.rs
updatehub/src/firmware/mod.rs
updatehub/src/http_api.rs
updatehub/src/main.rs
updatehub/src/object/installer/raw.rs
updatehub/src/object/macros.rs
updatehub/src/runtime_settings.rs
updatehub/src/settings.rs
updatehub/src/states/actor/mod.rs
updatehub/src/states/actor/stepper.rs
updatehub/src/states/direct_download.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/error.rs
updatehub/src/states/install.rs
updatehub/src/states/mod.rs
updatehub/src/states/park.rs
updatehub/src/states/poll.rs
updatehub/src/states/prepare_download.rs
updatehub/src/states/prepare_local_install.rs
updatehub/src/states/probe.rs
updatehub/src/states/reboot.rs
updatehub/src/states/validation.rs
updatehub/src/update_package/mod.rs

This PR includes a feel changes:
- A reworked commit message from #282 to fit our commit messaging style;
- Fix to the probe now (probe asp) rule that was not being handled properly in all use cases;
- Initial improvements to general execution logging

Some changes from dev branch

---

updatehub/src/main.rs
updatehub/src/settings.rs
updatehub/src/states/mod.rs

updatehub: Allow use of custom configuration for server

---

updatehub/src/logger.rs

updatehub: Remove colored log

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
.github/workflows/linux.yml
updatehub/Cargo.toml
updatehub/src/firmware/mod.rs
updatehub/src/firmware/tests.rs
updatehub/src/lib.rs
updatehub/src/runtime_settings.rs
updatehub/src/states/actor/info.rs
updatehub/src/states/actor/mod.rs
updatehub/src/states/actor/test.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/install.rs
updatehub/src/states/poll.rs
updatehub/src/states/probe.rs
updatehub/src/states/reboot.rs
updatehub/src/states/validation.rs
updatehub/src/tests.rs

general: Rework environment setup for testing

---

.github/workflows/linux.yml
Cargo.lock
updatehub-sdk/Cargo.toml

cicd: Add cargo bloat to check binary size changes

---

updatehub/src/http_api.rs
updatehub/src/states/machine/mod.rs
updatehub/src/states/mod.rs

This fixes some issues on master that I've found while rebasing #290

Some small fixes

---

.github/workflows/linux.yml

cicd: Restrict 'cargo bloat' check to MSRV

---

Cargo.lock
updatehub-cloud-sdk/Cargo.toml
updatehub-cloud-sdk/src/client.rs
updatehub/Cargo.toml

Update minor and major versions from dependencies

general: Update dependencies

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
.github/workflows/linux.yml
updatehub-cloud-sdk/src/client.rs
updatehub/tests/common.rs
updatehub/tests/successful_integration_test.rs

* Improve logging messages for object download;

Fix some CI bugs

---

updatehub/src/settings.rs
updatehub/tests/failed_integration_test.rs

updatehub: Display both parsing errors when using v1-parsing

---

updatehub/src/lib.rs
updatehub/src/main.rs
updatehub/src/mem_drain.rs
updatehub/tests/common.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

updatehub: Improve the output log for client commands

---

updatehub/src/states/machine/mod.rs
updatehub/src/states/poll.rs
updatehub/src/states/probe.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

This will be ready for merge once #315 is merged and this is probably rebased

Improve the "last operation" log returned by the API

---

updatehub/src/object/macros.rs
updatehub/src/utils/fs.rs
updatehub/src/utils/io.rs

updatehub: Improve logging of utility functions

---

updatehub/src/main.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

updatehub: Improve the probe output for client command

---

updatehub/src/main.rs

updatehub: Change to print the debug response instead result

---

.github/dependabot.yml

general: Add dependabot.yml

---

updatehub-cloud-sdk/src/lib.rs
updatehub/tests/failed_integration_test.rs

Improve invalid server response error

---

Cargo.lock
updatehub/Cargo.toml
updatehub/src/setup_mock_env.rs

Added a binary to setup the env and mock in order to run updatehub locally for
testing

updatehub: Add setup env test bin

---

updatehub-package-schema/src/lib.rs
updatehub-package-schema/src/uboot_env.rs
updatehub/src/object/info.rs
updatehub/src/object/installer/mod.rs
updatehub/src/object/installer/uboot_env.rs
updatehub/src/object/macros.rs
updatehub/src/object/mod.rs
updatehub/src/states/install.rs
updatehub/src/tests.rs

Add support for uboot-env install mode

---

updatehub/tests/failed_integration_test.rs

updatehub: update toml parsing error message

---

.github/workflows/linux.yml
Cargo.lock
updatehub-sdk/Cargo.toml
updatehub-sdk/examples/listener.rs
updatehub-sdk/src/error.rs
updatehub-sdk/src/lib.rs
updatehub-sdk/src/listener.rs

Add agent listener

---

updatehub-sdk/src/listener.rs
updatehub/src/states/mod.rs
updatehub/src/states/probe.rs
updatehub/tests/successful_integration_test.rs

updatehub-sdk: listener: Add support for Probe callbacks

---

updatehub-sdk/src/listener.rs

We now have a single storage for all callbacks and use the `State` as
indexing key.
The use of `u8` as key allows the reuse of `Eq` and `Hash`
implementations for our `State` type.

updatehub-sdk: listener: Reduce memory use and unify logic

---

updatehub-sdk/examples/listener.rs
updatehub-sdk/src/listener.rs

updatehub-sdk: doc: add a doc for the crate

---

updatehub/src/firmware/installation_set.rs
updatehub/src/firmware/mod.rs
updatehub/src/object/mod.rs
updatehub/src/runtime_settings.rs
updatehub/src/settings.rs
updatehub/src/states/download.rs
updatehub/src/states/mod.rs
updatehub/src/utils/definitions.rs
updatehub/src/utils/fs.rs
updatehub/src/utils/mod.rs
updatehub/tests/failed_integration_test.rs

This PR does some small code reworks and should not have behavior changes but
code style and code rework.

updatehub: Small code reworks

---

updatehub/src/main.rs

We improved the help and changed the command line arguments to use more
obvious name for the UpdateHub Agent, when running in daemon mode.

updatehub: Rework the cli interface so it is easier to use

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
.github/workflows/linux.yml
updatehub-sdk/src/api/mod.rs
updatehub/src/http_api.rs
updatehub/src/main.rs
updatehub/src/object/installer/mod.rs
updatehub/src/states/machine/mod.rs
updatehub/src/update_package/tests.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

Improve logging for CLI operations

---

updatehub/src/firmware/mod.rs
updatehub/src/states/mod.rs
updatehub/tests/failed_integration_test.rs
updatehub/tests/successful_integration_test.rs

Improve error handling of state change callback

---

updatehub/src/firmware/hook.rs

uh: More informative error message for when installation_set::active fails

---

Cargo.lock
shell.nix
updatehub/Cargo.toml

Upgrade dependencies

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
Cargo.lock
updatehub/Cargo.toml
updatehub/src/object/installer/copy.rs
updatehub/src/object/installer/imxkobs.rs
updatehub/src/object/installer/raw.rs
updatehub/src/object/installer/raw_delta.rs
updatehub/src/object/installer/tarball.rs
updatehub/src/object/installer/ubifs.rs
updatehub/src/object/installer/uboot_env.rs
updatehub/src/states/direct_download.rs
updatehub/src/states/download.rs
updatehub/src/states/entry_point.rs
updatehub/src/states/install.rs
updatehub/src/states/prepare_local_install.rs
updatehub/src/states/probe.rs
updatehub/src/states/reboot.rs
updatehub/src/states/validation.rs
updatehub/src/utils/log.rs
updatehub/src/utils/mod.rs
updatehub/tests/failed_integration_test.rs

uh: Add log module to utils to easily log Results and Options

---

updatehub/src/utils/delta.rs

This should ensure output file has been fully written when the function returns

uh: Add flush to delta::clone

---

Cargo.lock
updatehub/Cargo.toml
updatehub/src/object/installer/copy.rs
updatehub/src/object/installer/flash.rs
updatehub/src/object/installer/imxkobs.rs
updatehub/src/object/installer/mod.rs
updatehub/src/object/installer/raw.rs
updatehub/src/object/installer/tarball.rs
updatehub/src/object/macros.rs
updatehub/src/utils/fs.rs

The install-if-different handling macro has been reworked to be fully async and made into a function. Related functions have also been updated to be fully async

Rework handling install if different

---

updatehub/Cargo.toml

Signed-off-by: Rodrigo M. Duarte <rodrigo.duarte@ossystems.com.br>

updatehub/Cargo: Fix the cargo dependencies
